# Generated by Django 2.2.5 on 2019-09-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'message log', 'verbose_name_plural': 'message log '},
        ),
    ]
